services:
  pgsql:
    image: 'postgres:18'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - ekoreader
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
      retries: 3
      timeout: 5s

volumes:
  pgdata:
    driver: local

networks:
  ekoreader:
    driver: bridge